import streamlit as st
import requests

# Define the API endpoints
SCRAPE_ENDPOINT = "https://localhost:5000/handle_user_prompt"
QA_ENDPOINT = "https://localhost:5000/handle_user_prompt"

# Define the UI layout
st.set_page_config(
    page_title="Autism Parent Support (Paññā)",
    page_icon="🧩",
    layout="wide"
)

# Header with a shorter green block
st.markdown(
    """
    <div style="background-color:#4CAF50;padding:6px;border-radius:10px;">
    <h1 style="color:white;text-align:center;">Autism Parent Support (Paññā)</h1>
    </div>
    """,
    unsafe_allow_html=True
)

# Subheader
st.header("Empowering the Autism Community with Love, Knowledge, and Understanding")

# Description
st.markdown("Paññā bot is here to help and support parents of children with autism. Feel free to ask questions or seek information about autism-related topics.")

# Input field with an example question as a placeholder (faded)
example_question = """
*Example Question:*
I'm seeking guidance regarding my 11-year-old son, who is autistic and also has ADHD. Recently, he has developed a habit of chewing on cloth, particularly during moments of intense emotions or stress. Could you provide insights into this behavior? Why might he be doing this, and how can I understand and support him better in these situations? Additionally, could you offer strategies or approaches to help him cope with his intense feelings in a healthier way?
"""

question = st.text_area("Ask a Short Question (e.g., 'Chewing behavior in my son')", value="", help="Type your question here...", key="question_textarea",
                       height=100, placeholder=example_question)

if st.button("Submit", key="get_insights_button", help="Click to get insights on your question"):
    # Call the QA endpoint to get the answer
    data = {"prompt": question}
    response = requests.post(QA_ENDPOINT, json=data, verify=False)
    result = response.json()
    content_to_print = result["result"]["choices"][0]["message"]["content"]

    # Display the answer
    st.markdown('<p style="color:green;"><strong>Paññā Response:</strong></p>', unsafe_allow_html=True)
    st.markdown(content_to_print)

# Experimental Disclaimer
st.warning("This is an experimental AI-powered service. Responses generated by the AI bot cannot be treated as medical advice. Please consult a healthcare professional for medical concerns.")

# Footer
st.markdown("---")
st.write("For additional support or inquiries, please contact us at contact@panna.x10.mx")
